[package]
name = "safe_dbc"
version = "0.1.0"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-keccak = { version = "2.0.0", features = ["sha3"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.7.1"

[dependencies.ed25519]
  version = "1"
  package = "ed25519-dalek"
  features = [ "serde" ]

[dependencies.serde]
  version = "1.0.111"
  features = [ "derive", "rc" ]
